### ISSUE TITLE
Unable to see the see the About page in http://cellocad.org/ without logging in.

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/cello#3]
The user needs to login to see the about page. Please make the about page public.Its extremely inconvenient when one is trying to look up the documentation or the resources.

**Comment by btamayo** [comment]
Wrote a quick PR for it here: https://github.com/CIDARLAB/cello/pull/9 if this is something you'd like.

**Comment by PrashantVaidyanathan** [comment]
Thanks. This has been fixed in commit: 27f6354f41cd2997610e79e2a41ded61f2c3fa91
