### ISSUE TITLE
Could not run " python cell_client.py submit"

### ISSUE THREAD

**Issue by danielchen26** [CIDARLAB/cello#39]
When typed " python cell_client.py submit" in terminal in the pycello folder. It gives me the following error. Also, in your README file, it seems that you missed an argument in the command line. How do you install "cello" to the shell?

```
File "cello_client.py", line 292
    print gb_feature.location, gb_feature.type, gb_feature.qualifiers['label'], gb_feature.extract(gb_record.seq)
                   ^
SyntaxError: invalid syntax
```

**Comment by tim-tx** [comment]
Using Python 3 instead of Python 2 would cause this.

Please give a specific reference to the README.

We don't have any kind of install script, it's expected that you run Cello from the source folder where you built it.

**Comment by danielchen26** [comment]
Thanks for the reply. I will try python2. for the README file I am referring to the file in the tools/pycello/README. 
in the REDME file, it writes:

```
Install:

```
$ pip install --editable .
```


Test installation:

+ If successful, the installation creates a shell command called 'cello'.  

```
$ cello
```
```

**Comment by tim-tx** [comment]
Make sure you include the final period in

    $ pip install --editable .

If this doesn't work please post any error messages.

**Comment by danielchen26** [comment]
It works. Now I have installed the command line "cello" in a virtual environment with conda python2. Thanks for your help
