### ISSUE TITLE
Location of org.cellocad.BU.netsynth.NetSynth

### ISSUE THREAD

**Issue by objorn** [CIDARLAB/cello#40]
I see an import for `org.cellocad.BU.netsynth.NetSynth` in
[org.cellocad.MIT.dnacompiler](https://github.com/CIDARLAB/cello/blob/develop/src/main/java/org/cellocad/MIT/dnacompiler/DNACompiler.java), but I can't find BU.netsynth in this repo. Where is BU.netsynth?

**Comment by tim-tx** [comment]
The source is here: https://github.com/CIDARLAB/NetlistSynthesizer
